aa: rand-m9-mstd0.5-inc1
amp: false
apex_amp: false
aug_splits: 0
batch_size: 128
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 10
cos_reg_component: 0
crop_pct: null
cutmix: 1.0
cutmix_minmax: null
data: ../../Dataset/Landscape Classification/
decay_epochs: 15
decay_rate: 0.1
dist_bn: ''
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.2
epochs: 300
eval_metric: top1
gp: null
hflip: 0.5
img_size: 224
initial_checkpoint: ''
interpolation: ''
jsd: false
local_rank: 0
log_interval: 50
lr: 0.001
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-05
mixup: 0.8
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: TerrainDeepViT_S
model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_prefetcher: false
no_resume_opt: false
num_classes: 5
opt: adamw
opt_betas: null
opt_eps: null
output: ../output/terraindeepvit_S
patience_epochs: 10
pin_mem: false
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.25
resplit: false
resume: "/home/mohanakrishna/Development/GSSoC/output/terraindeepvit_S/train/20240615-025115-TerrainDeepViT_S-224/last.pth.tar"
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
torchscript: false
train_interpolation: random
tta: 0
use_lmdb: false
use_multi_epochs_loader: false
use_repeated_aug: false
validation_batch_size_multiplier: 1
vflip: 0.0
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 0.05
workers: 8
