# -*- coding: utf-8 -*-
"""AI_MINIPROJECT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oq9lY3qB1Jnw8Evaz6H-QQS_QrdAjLaJ
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import numpy as np

df=pd.read_csv('/content/salary_data.csv')

print(df.head(10))
print()
print(df.tail(10))

X = df[['YearsExperience']]
y = df['Salary']

plt.plot(X, y, color='red')
plt.scatter(X,y, color='blue')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.90, random_state=42)

model=LinearRegression()
model.fit(X_train, y_train)

m=model.coef_
c=model.intercept_
print(m)
print()
print(c)

y_pred=model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f'Root Mean Squared Error on Test Set: {rmse}')

user_experience = float(input("Enter the number of years of experience: "))

user_salary_prediction = model.predict(np.array([[user_experience]]))
print(f"Predicted Salary for {user_experience} years of experience: ${user_salary_prediction[0]:,.2f}")

plt.scatter(X_test, y_test, color='black', label='Actual Salaries')
plt.plot(X_test, y_pred, color='blue', linewidth=3, label='Regression Line')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.title('Linear Regression Model')
plt.legend()
plt.show()