from .cross_entropy import LabelSmoothingCrossEntropy, SoftTargetCrossEntropy, SoftTargetCrossEntropyCosReg
from .jsd import JsdCrossEntropy
from .asymmetric_loss import AsymmetricLossMultiLabel, AsymmetricLossSingleLabel