weights: ''
cfg: ./models/yolov5x.yaml
data: /content/yolo-drone-detection-dataset/drone_dataset/data.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 20
batch_size: 16
imgsz: 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: yolov5x_results
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolov5x_results
