# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tosgF9FuNCbtm_s5_jFN_GF7YkWZZSBm
"""

!pip install gradio

from keras.models import model_from_json
import numpy as np
from PIL import Image
import gradio as gr

json_file = open(r"model.json", 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
model.load_weights(r"model.h5", by_name=True)

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

def classify_image(image):
    try:
        img = Image.open(image.name)
        img = img.resize((28, 28))
        img_array = np.array(img.convert('L')) / 255.0
        img_array = np.expand_dims(img_array, axis=0)
        img_array = np.expand_dims(img_array, axis=-1)
        prediction = model.predict(img_array)
        predicted_class = np.argmax(prediction)
        return class_names[predicted_class]
    except Exception as e:
        return str(e)

iface = gr.Interface(fn=classify_image, inputs="file", outputs="text", title="Fashion MNIST IMAGE CLASSIFICATION")
iface.launch()